const PRIMARY_HOST = 'coastslide.com';
const OLD_HOSTS = new Set(['coastsliding.com', 'www.coastsliding.com', 'www.coastslide.com']);
const CONTACT_EMAIL = 'coastsliding@gmail.com';
const PHOTO_EXTENSIONS = ['jpg', 'jpeg', 'png', 'webp', 'avif', 'JPG', 'JPEG', 'PNG', 'WEBP', 'AVIF'];
const PHOTO_DIRS = ['images', 'imagenes', 'images/svg'];

const REPLACEMENTS = [
  [/https:\/\/coastsliding\.com/g, 'https://coastslide.com'],
  [/http:\/\/coastsliding\.com/g, 'https://coastslide.com'],
  [/www\.coastsliding\.com/g, 'coastslide.com'],
  [/coastsliding\.com/g, 'coastslide.com'],
  [/\+1-305-555-7543/g, '+17866593290'],
  [/\+13055557543/g, '+17866593290'],
  [/13055557543/g, '17866593290'],
  [/3055557543/g, '17866593290'],
  [/\(305\) 555-7543/g, '(786) 659-3290'],
  [/\(954\) 555-7543/g, '(786) 659-3290'],
  [/\(561\) 555-7543/g, '(786) 659-3290'],
  [/305-555-7543/g, '786-659-3290'],
  [/954-555-7543/g, '786-659-3290'],
  [/561-555-7543/g, '786-659-3290'],
  [/305\.555\.7543/g, '786.659.3290'],
  [/\s*link\('pages\/florida-keys\.html', 'Florida Keys'\) \+/g, ''],
  [/\s*mob\('pages\/florida-keys\.html', 'Florida Keys'\) \+/g, ''],
  [/\['miami', 'broward', 'palm', 'keys'\]/g, "['miami', 'broward', 'palm']"],
  [/<option>Florida Keys<\/option>/g, ''],
  [/Miami-Dade, Broward, Palm Beach and the Florida Keys/g, 'Miami-Dade, Broward and Palm Beach']
];

const DESIGN_FIX_CSS = `
<style id="cs-worker-fixes">
.photo-strip{grid-template-columns:repeat(3,minmax(0,1fr))!important;max-width:1180px;margin:0 auto;background:#fff;box-shadow:0 2px 12px rgba(11,98,141,.12)}
.ps-cell{aspect-ratio:16/11!important;min-height:230px;background:linear-gradient(135deg,#EBF5FC,#fff)}
.ps-cell img,.svc-img img{display:block!important;width:100%!important;height:100%!important;object-fit:cover!important}.ps-cell img{filter:brightness(.86)!important}.ps-cell:hover img{filter:brightness(1)!important}
.rpanel.active{display:grid;grid-template-columns:minmax(0,1.05fr) minmax(360px,.95fr);align-items:stretch;border-radius:14px!important;overflow:hidden!important}.rp-photo{min-height:520px;background:linear-gradient(145deg,#073F5F,#0B628D 58%,#087D87)!important}.rp-photo img{display:block!important;opacity:1!important;visibility:visible!important;position:absolute!important;inset:0!important;width:100%!important;height:100%!important;object-fit:cover!important;filter:brightness(.72) saturate(1.05)!important}.rp-photo-overlay{background:linear-gradient(160deg,rgba(4,47,73,.84) 0%,rgba(8,125,135,.42) 100%)!important}.rp-stat{min-width:0;padding:14px 12px!important;background:rgba(0,29,49,.48)!important;border-color:rgba(255,255,255,.34)!important}.rp-stat-n{font-size:clamp(18px,1.8vw,22px)!important;line-height:1.05!important;white-space:nowrap;color:#fff!important;text-shadow:0 2px 8px rgba(0,0,0,.35)}.rp-stat-l{font-size:9px!important;line-height:1.25!important;color:#fff!important;opacity:.94!important;overflow-wrap:anywhere}.rp-tag,.rp-city{color:#fff!important;text-shadow:0 1px 5px rgba(0,0,0,.32)}
@media(max-width:1024px){.rpanel.active{grid-template-columns:1fr!important;border-radius:14px!important}.photo-strip{grid-template-columns:1fr!important}.ps-cell{aspect-ratio:16/10!important}}
@media(max-width:768px){.photo-strip .ps-cell:nth-child(3){display:block!important}.rp-photo{min-height:0!important;height:auto!important;display:flex!important;flex-direction:column!important;background:#073F5F!important;aspect-ratio:auto!important}.rp-photo img{position:relative!important;inset:auto!important;height:auto!important;aspect-ratio:16/10!important;object-position:center!important;filter:brightness(.82) saturate(1.04)!important;flex:0 0 auto!important}.rp-photo-overlay{display:none!important}.rp-photo-content{position:relative!important;inset:auto!important;padding:22px 18px 20px!important;justify-content:flex-start!important;background:linear-gradient(145deg,#073F5F,#084F73 58%,#087D87)!important;gap:10px!important}.rp-tag{font-size:9px!important;letter-spacing:1.6px!important;margin-bottom:0!important}.rp-title{font-size:clamp(32px,10vw,42px)!important;line-height:1!important;margin-bottom:4px!important}.rp-cities{gap:7px!important;margin-bottom:8px!important}.rp-city{font-size:10px!important;padding:5px 10px!important;line-height:1.15!important}.rp-stats{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important}.rp-stat{padding:10px 8px!important;border-radius:8px!important}.rp-stat-n{font-size:16px!important;white-space:normal!important;line-height:1.1!important}.rp-stat-l{font-size:8px!important;letter-spacing:.5px!important;line-height:1.2!important}.rp-info{padding:24px 18px!important;gap:16px!important}.rp-info h3{font-size:21px!important;line-height:1.2!important}.rp-info p{font-size:14px!important;line-height:1.65!important}.rp-check-list{grid-template-columns:1fr!important;gap:8px!important}}
@media(max-width:520px){.region-tabs{gap:8px!important}.rtab{flex:1 1 100%!important;justify-content:center!important}.rp-photo img{aspect-ratio:4/3!important}.rp-stats{grid-template-columns:1fr 1fr!important}.rp-stat-n{white-space:normal!important}}
@media(max-width:380px){.rp-stats{grid-template-columns:1fr!important}.rp-title{font-size:31px!important}}
</style>`;

function shouldRewrite(contentType) { return /text\/html|text\/css|application\/javascript|text\/javascript|application\/json|text\/plain|application\/xml|text\/xml/i.test(contentType || ''); }
function clean(value) { return String(value || '').replace(/[\r\n]+/g, ' ').trim().slice(0, 1200); }
function slug(value) { return String(value || '').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, ''); }
function unique(list) { const seen = new Set(); return list.filter((item) => item && !seen.has(item) && seen.add(item)); }
function firstFormValue(form, names) { for (const name of names) { const value = clean(form.get(name)); if (value) return value; } return ''; }
function json(body, status = 200) { return new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store', 'access-control-allow-origin': '*' } }); }
function assetUrl(request, path) { const url = new URL(request.url); url.pathname = '/' + path.replace(/^\/+/, ''); url.search = ''; return url; }
async function assetLooksReal(env, request, path) { const response = await env.ASSETS.fetch(new Request(assetUrl(request, path), request)); if (!response.ok) return false; const type = (response.headers.get('content-type') || '').toLowerCase(); if (type.includes('text/html') || type.includes('svg')) return false; const size = Number(response.headers.get('content-length') || 0); if (size && size < 4096) return false; return true; }
function photoCandidates(src, alt) { const match = src.match(/(?:^|\/)(?:images|imagenes)(?:\/svg)?\/([^\/]+?)\.(?:jpg|jpeg|png|webp|avif)(?:\?.*)?$/i); if (!match) return []; const rawName = match[1]; const number = (rawName.match(/^\d+/) || [rawName])[0]; const names = unique([number, rawName, slug(alt)]); const paths = []; for (const dir of PHOTO_DIRS) for (const name of names) for (const ext of PHOTO_EXTENSIONS) paths.push(`${dir}/${name}.${ext}`); return unique(paths); }
async function resolvePhotoSrc(env, request, src, alt) { for (const path of photoCandidates(src, alt)) if (await assetLooksReal(env, request, path)) return '/' + path; return src; }
async function rewriteImageSources(html, env, request) { const imgPattern = /<img\b([^>]*?)\bsrc="([^"]+)"([^>]*)>/gi; const matches = [...html.matchAll(imgPattern)]; let rewritten = html; for (const match of matches) { const full = match[0]; const src = match[2]; if (!/\/(?:images|imagenes)\//i.test(src) && !/(?:^|\.\/)images\//i.test(src)) continue; const attrs = `${match[1]} ${match[3]}`; const alt = (attrs.match(/\balt="([^"]*)"/i) || [])[1] || ''; const next = await resolvePhotoSrc(env, request, src, alt); if (next !== src) rewritten = rewritten.replace(full, full.replace(`src="${src}"`, `src="${next}?v=photo-live"`)); } return rewritten; }
async function normalizeText(text, contentType, env, request) { let value = REPLACEMENTS.reduce((current, pair) => current.replace(pair[0], pair[1]), text); if (/text\/css/i.test(contentType)) value = value.replace(/\.photo-strip\{display:grid;grid-template-columns:repeat\(4,1fr\);/g, '.photo-strip{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));').replace(/\.rp-photo img\{display:none!important\}/g, '.rp-photo img{display:block!important;opacity:1!important;visibility:visible!important}').replace(/\.ps-cell\{position:relative;overflow:hidden;aspect-ratio:3\/4\}/g, '.ps-cell{position:relative;overflow:hidden;aspect-ratio:16/11;min-height:230px}'); if (/text\/html/i.test(contentType)) { value = await rewriteImageSources(value, env, request); if (!value.includes('cs-worker-fixes')) value = value.replace('</head>', DESIGN_FIX_CSS + '</head>'); } return value; }
function buildLead(form, request) { return { name: firstFormValue(form, ['name', 'home-name', 'contact-name', 'cs-field-0-0', 'cs-field-1-0']), phone: firstFormValue(form, ['phone', 'home-phone', 'contact-phone', 'cs-field-0-1', 'cs-field-1-1']), email: firstFormValue(form, ['email', 'home-email', 'contact-email', 'cs-field-0-2', 'cs-field-1-2']), area: firstFormValue(form, ['area', 'county', 'city', 'home-county', 'contact-area', 'cs-field-0-3', 'cs-field-1-3']), problem: firstFormValue(form, ['problem', 'repair', 'issue', 'home-repair', 'contact-problem', 'cs-field-0-4', 'cs-field-1-4']), details: firstFormValue(form, ['details', 'message', 'notes', 'home-details', 'contact-details', 'cs-field-0-5', 'cs-field-1-5']), source: request.headers.get('referer') || 'Direct website form' }; }
function leadBody(lead) { return ['New CoastSlide contact request', '', 'Name: ' + lead.name, 'Phone: ' + lead.phone, 'Email: ' + lead.email, 'City or Area: ' + (lead.area || 'Not provided'), 'Type of Problem: ' + lead.problem, 'Details: ' + (lead.details || 'Not provided'), 'Source Page: ' + lead.source].join('\n'); }
async function sendLeadWithFormSubmit(lead) { const payload = { _subject: 'New CoastSlide Contact Request', _template: 'table', _captcha: 'false', _replyto: lead.email, name: lead.name, phone: lead.phone, email: lead.email, area: lead.area || 'Not provided', problem: lead.problem, details: lead.details || 'Not provided', message: leadBody(lead), source_page: lead.source }; const response = await fetch('https://formsubmit.co/ajax/' + CONTACT_EMAIL, { method: 'POST', headers: { Accept: 'application/json', 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); let result = {}; try { result = await response.json(); } catch (error) { result = { success: String(response.ok) }; } return { ok: response.ok && String(result.success).toLowerCase() === 'true', status: response.status, result }; }
async function handleContact(request) { if (request.method === 'OPTIONS') return json({ ok: true }); if (request.method !== 'POST') return json({ ok: false, error: 'Method not allowed' }, 405); const form = await request.formData(); if (clean(form.get('company'))) return json({ ok: true }); const lead = buildLead(form, request); if (!lead.name || !lead.phone || !lead.email || !lead.problem) return json({ ok: false, error: 'missing_required_fields' }, 400); const delivery = await sendLeadWithFormSubmit(lead); if (delivery.ok) return json({ ok: true, delivery: 'formsubmit' }); const message = clean(delivery.result && delivery.result.message); const activationRequired = /activation/i.test(message); return json({ ok: false, error: activationRequired ? 'activation_required' : 'email_delivery_failed', message: activationRequired ? 'The email form needs one-time activation.' : 'Email delivery failed.' }, activationRequired ? 503 : 502); }

export default { async fetch(request, env) { const url = new URL(request.url); if (OLD_HOSTS.has(url.hostname)) { url.hostname = PRIMARY_HOST; url.protocol = 'https:'; return Response.redirect(url.toString(), 301); } if (url.pathname === '/api/contact') return handleContact(request); const response = await env.ASSETS.fetch(request); const contentType = response.headers.get('content-type') || ''; if (!shouldRewrite(contentType)) return response; const headers = new Headers(response.headers); headers.delete('content-length'); headers.set('cache-control', 'no-store, no-cache, must-revalidate, max-age=0'); return new Response(await normalizeText(await response.text(), contentType, env, request), { status: response.status, statusText: response.statusText, headers }); } };
